services:
  - type: web
    name: momenthub
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: momenthub-db
          property: connectionString

databases:
  - name: momenthub-db
    region: frankfurt
    plan: free
    databaseName: momenthub
    user: momenthub_user
